

AIRPORT_TO_CITY_100 = {
    "Frankfurt am Main Airport": ("Frankfurt", "Germany"),
    "Istanbul Airport": ("Istanbul", "Turkey"),
    "Amsterdam Airport Schiphol": ("Amsterdam", "Netherlands"),
    "Charles de Gaulle International Airport": ("Paris", "France"),
    "Chicago O'Hare International Airport": ("Chicago", "United States"),
    "Dallas Fort Worth International Airport": ("Dallas", "United States"),
    "Beijing Capital International Airport": ("Beijing", "China"),
    "Hartsfield Jackson Atlanta International Airport": ("Atlanta", "United States"),
    "Munich Airport": ("Munich", "Germany"),
    "Shanghai Pudong International Airport": ("Shanghai", "China"),
    "Dubai International Airport": ("Dubai", "United Arab Emirates"),
    "London Heathrow Airport": ("London", "United Kingdom"),
    "Domodedovo International Airport": ("Moscow", "Russia"),
    "Guangzhou Baiyun International Airport": ("Guangzhou", "China"),
    "Denver International Airport": ("Denver", "United States"),
    "Sheremetyevo International Airport": ("Moscow", "Russia"),
    "London Gatwick Airport": ("London", "United Kingdom"),
    "John F Kennedy International Airport": ("New York", "United States"),
    "Adolfo Su\u00e1rez Madrid\u2013Barajas Airport": ("Madrid", "Spain"),
    "Barcelona International Airport": ("Barcelona", "Spain"),
    "Vienna International Airport": ("Vienna", "Austria"),
    "George Bush Intercontinental Houston Airport": ("Houston", "United States"),
    "Hamad International Airport": ("Doha", "Qatar"),
    "Z\u00fcrich Airport": ("Zurich", "Switzerland"),
    "Leonardo da Vinci\u2013Fiumicino Airport": ("Rome", "Italy"),
    "Los Angeles International Airport": ("Los Angeles", "United States"),
    "Lester B. Pearson International Airport": ("Toronto", "Canada"),
    "D\u00fcsseldorf Airport": ("Dusseldorf", "Germany"),
    "Brussels Airport": ("Brussels", "Belgium"),
    "Miami International Airport": ("Miami", "United States"),
    "London Stansted Airport": ("London", "United Kingdom"),
    "Newark Liberty International Airport": ("New York", "United States"),
    "Charlotte Douglas International Airport": ("Charlotte", "United States"),
    "Incheon International Airport": ("Seoul", "South Korea"),
    "Hong Kong International Airport": ("Hong Kong", "Hong Kong"),
    "Manchester Airport": ("Manchester", "United Kingdom"),
    "Dublin Airport": ("Dublin", "Ireland"),
    "Suvarnabhumi Airport": ("Bangkok", "Thailand"),
    "Chengdu Shuangliu International Airport": ("Chengdu", "China"),
    "Singapore Changi Airport": ("Singapore", "Singapore"),
    "Xi'an Xianyang International Airport": ("Xian", "China"),
    "Kunming Changshui International Airport": ("Kunming", "China"),
    "Detroit Metropolitan Wayne County Airport": ("Detroit", "United States"),
    "Copenhagen Kastrup Airport": ("Copenhagen", "Denmark"),
    "V\u00e1clav Havel Airport Prague": ("Prague", "Czech Republic"),
    "Minneapolis-St Paul International/Wold-Chamberlain Airport": ("Minneapolis", "United States"),
    "Washington Dulles International Airport": ("Washington", "United States"),
    "McCarran International Airport": ("Las Vegas", "United States"),
    "Stockholm-Arlanda Airport": ("Stockholm", "Sweden"),
    "Philadelphia International Airport": ("Philadelphia", "United States"),
    "Shenzhen Bao'an International Airport": ("Shenzhen", "China"),
    "Vnukovo International Airport": ("Moscow", "Russia"),
    "Chongqing Jiangbei International Airport": ("Chongqing", "China"),
    "Pulkovo Airport": ("Saint Petersburg", "Russia"),
    "Paris-Orly Airport": ("Paris", "France"),
    "Narita International Airport": ("Tokyo", "Japan"),
    "Palma De Mallorca Airport": ("Palma De Mallorca", "Spain"),
    "San Francisco International Airport": ("San Francisco", "United States"),
    "Taiwan Taoyuan International Airport": ("Taipei", "Taiwan"),
    "Malpensa International Airport": ("Milan", "Italy"),
    "Montreal / Pierre Elliott Trudeau International Airport": ("Montreal", "Canada"),
    "Indira Gandhi International Airport": ("Delhi", "India"),
    "Humberto Delgado Airport (Lisbon Portela Airport)": ("Lisbon", "Portugal"),
    "Kuala Lumpur International Airport": ("Kuala Lumpur", "Malaysia"),
    "Eleftherios Venizelos International Airport": ("Athens", "Greece"),
    "Orlando International Airport": ("Orlando", "United States"),
    "King Abdulaziz International Airport": ("Jeddah", "Saudi Arabia"),
    "M\u00e1laga Airport": ("Malaga", "Spain"),
    "Helsinki Vantaa Airport": ("Helsinki", "Finland"),
    "Phoenix Sky Harbor International Airport": ("Phoenix", "United States"),
    "Geneva Cointrin International Airport": ("Geneva", "Switzerland"),
    "Seattle Tacoma International Airport": ("Seattle", "United States"),
    "Warsaw Chopin Airport": ("Warsaw", "Poland"),
    "General Edward Lawrence Logan International Airport": ("Boston", "United States"),
    "Berlin-Tegel Airport": ("Berlin", "Germany"),
    "Hangzhou Xiaoshan International Airport": ("Hangzhou", "China"),
    "Fort Lauderdale Hollywood International Airport": ("Fort Lauderdale", "United States"),
    "Oslo Lufthavn": ("Oslo", "Norway"),
    "Sabiha G\u00f6k\u00e7en International Airport": ("Istanbul", "Turkey"),
    "Addis Ababa Bole International Airport": ("Addis Ababa", "Ethiopia"),
    "Mohammed V International Airport": ("Casablanca", "Morocco"),
    "Guarulhos - Governador Andr\u00e9 Franco Montoro International Airport": ("Sao Paulo", "Brazil"),
    "Alicante International Airport": ("Alicante", "Spain"),
    "Cologne Bonn Airport": ("Cologne", "Germany"),
    "Changsha Huanghua International Airport": ("Changsha", "China"),
    "Stuttgart Airport": ("Stuttgart", "Germany"),
    "Licenciado Benito Juarez International Airport": ("Mexico City", "Mexico"),
    "Wuhan Tianhe International Airport": ("Wuhan", "China"),
    "Hamburg Airport": ("Hamburg", "Germany"),
    "Edinburgh Airport": ("Edinburgh", "United Kingdom"),
    "Xiamen Gaoqi International Airport": ("Xiamen", "China"),
    "Salt Lake City International Airport": ("Salt Lake City", "United States"),
    "Gran Canaria Airport": ("Las Palmas De Gran Canaria", "Spain"),
    "Budapest Liszt Ferenc International Airport": ("Budapest", "Hungary"),
    "London Luton Airport": ("London", "United Kingdom"),
    "Chhatrapati Shivaji International Airport": ("Mumbai", "India"),
    "Ben Gurion International Airport": ("Tel Aviv-Yafo", "Israel"),
    "Sydney Kingsford Smith International Airport": ("Sydney", "Australia"),
    "Abu Dhabi International Airport": ("Abu Dhabi", "United Arab Emirates"),
    "Tenerife South Airport": ("Tenerife", "Spain"),

    # --- Extended set: additional airports appearing at N=120/N=200 scale ---
    "Il Caravaggio International Airport": ("Bergamo", "Italy"),
    "Nanjing Lukou Airport": ("Nanjing", "China"),
    "Sharjah International Airport": ("Sharjah", "United Arab Emirates"),
    "Nice-C\u00f4te d'Azur Airport": ("Nice", "France"),
    "Brussels South Charleroi Airport": ("Charleroi", "Belgium"),
    "Cairo International Airport": ("Cairo", "Egypt"),
    "Beijing Daxing International Airport": ("Beijing", "China"),
    "Ronald Reagan Washington National Airport": ("Washington", "United States"),
    "Vancouver International Airport": ("Vancouver", "Canada"),
    "Liuting Airport": ("Qingdao", "China"),
    "Zhengzhou Xinzheng International Airport": ("Zhengzhou", "China"),
    "Tianjin Binhai International Airport": ("Tianjin", "China"),
    "Malta International Airport": ("Valletta", "Malta"),
    "Lyon Saint-Exup\u00e9ry Airport": ("Lyon", "France"),
    "Canc\u00fan International Airport": ("Cancun", "Mexico"),
    "Marseille Provence Airport": ("Marseille", "France"),
    "Kansai International Airport": ("Osaka", "Japan"),
    "Birmingham International Airport": ("Birmingham", "United Kingdom"),
    "Henri Coanda International Airport": ("Bucharest", "Romania"),
    "Tocumen International Airport": ("Panama City", "Panama"),
    "Tokyo Haneda International Airport": ("Tokyo", "Japan"),
    "Taoxian Airport": ("Shenyang", "China"),
    "King Khaled International Airport": ("Riyadh", "Saudi Arabia"),
    "Berlin-Sch\u00f6nefeld Airport": ("Berlin", "Germany"),
    "OR Tambo International Airport": ("Johannesburg", "South Africa"),
    "Soekarno-Hatta International Airport": ("Jakarta", "Indonesia"),
    "Ninoy Aquino International Airport": ("Manila", "Philippines"),
    "Taiping Airport": ("Harbin", "China"),
    "El Dorado International Airport": ("Bogota", "Colombia"),
    "Zhoushuizi Airport": ("Dalian", "China"),
    "Longdongbao Airport": ("Guiyang", "China"),
    "La Guardia Airport": ("New York", "United States"),
    "Krak\u00f3w John Paul II International Airport": ("Krakow", "Poland"),
    "Haikou Meilan International Airport": ("Haikou", "China"),
    "Bristol Airport": ("Bristol", "United Kingdom"),
    "Tolmachevo Airport": ("Novosibirsk", "Russia"),
    "Venice Marco Polo Airport": ("Venice", "Italy"),
    "Nanning Wuxu Airport": ("Nanning", "China"),
    "Boryspil International Airport": ("Kyiv", "Ukraine"),
    "Tampa International Airport": ("Tampa", "United States"),
    "Don Mueang International Airport": ("Bangkok", "Thailand"),
    "Baltimore/Washington International Thurgood Marshall Airport": ("Baltimore", "United States"),
    "Chicago Midway International Airport": ("Chicago", "United States"),
    "EuroAirport Basel-Mulhouse-Freiburg Airport": ("Basel", "Switzerland"),
    "Calgary International Airport": ("Calgary", "Canada"),
    "Fuzhou Changle International Airport": ("Fuzhou", "China"),
    "Jomo Kenyatta International Airport": ("Nairobi", "Kenya"),
    "Francisco de S\u00e1 Carneiro Airport": ("Porto", "Portugal"),
    "Yaoqiang Airport": ("Jinan", "China"),
    "Bologna Guglielmo Marconi Airport": ("Bologna", "Italy"),
    "Riga International Airport": ("Riga", "Latvia"),
    "Antalya International Airport": ("Antalya", "Turkey"),
    "Houari Boumediene Airport": ("Algiers", "Algeria"),
    "Shanghai Hongqiao International Airport": ("Shanghai", "China"),
    "Valencia Airport": ("Valencia", "Spain"),
    "\u00dcr\u00fcmqi Diwopu International Airport": ("Urumqi", "China"),
    "Faro Airport": ("Faro", "Portugal"),
    "Brisbane International Airport": ("Brisbane", "Australia"),
    "Eindhoven Airport": ("Eindhoven", "Netherlands"),
    "Queen Alia International Airport": ("Amman", "Jordan"),
    "Tan Son Nhat International Airport": ("Ho Chi Minh City", "Vietnam"),
    "Jorge Ch\u00e1vez International Airport": ("Lima", "Peru"),
    "Melbourne International Airport": ("Melbourne", "Australia"),
    "Menara Airport": ("Marrakesh", "Morocco"),
    "Portland International Airport": ("Portland", "United States"),
    "Koltsovo Airport": ("Yekaterinburg", "Russia"),
    "Naples International Airport": ("Naples", "Italy"),
    "Pisa International Airport": ("Pisa", "Italy"),
    "Larnaca International Airport": ("Larnaca", "Cyprus"),
    "Glasgow International Airport": ("Glasgow", "United Kingdom"),
    "St Louis Lambert International Airport": ("St Louis", "United States"),
    "Luxembourg-Findel International Airport": ("Luxembourg", "Luxembourg"),
    "Nantes Atlantique Airport": ("Nantes", "France"),
    "Ningbo Lishe International Airport": ("Ningbo", "China"),
    "Tunis Carthage International Airport": ("Tunis", "Tunisia"),
    "Kuwait International Airport": ("Kuwait City", "Kuwait"),
    "Muscat International Airport": ("Muscat", "Oman"),
    "Lanzhou Zhongchuan Airport": ("Lanzhou", "China"),
    "Taiyuan Wusu Airport": ("Taiyuan", "China"),
    "Nanchang Changbei International Airport": ("Nanchang", "China"),
    "San Diego International Airport": ("San Diego", "United States"),
    "Fuerteventura Airport": ("Fuerteventura", "Spain"),
    "Thessaloniki Macedonia International Airport": ("Thessaloniki", "Greece"),
    "Guilin Liangjiang International Airport": ("Guilin", "China"),
    "Lanzarote Airport": ("Lanzarote", "Spain"),
    "Ngurah Rai (Bali) International Airport": ("Denpasar", "Indonesia"),
    "Viracopos International Airport": ("Campinas", "Brazil"),
    "Shijiazhuang Daguocun International Airport": ("Shijiazhuang", "China"),
    "Heraklion International Nikos Kazantzakis Airport": ("Heraklion", "Greece"),
    "Bordeaux-M\u00e9rignac Airport": ("Bordeaux", "France"),
    "Paris Beauvais Till\u00e9 Airport": ("Paris", "France"),
    "Hannover Airport": ("Hannover", "Germany"),
    "Tashkent International Airport": ("Tashkent", "Uzbekistan"),
    "Yantai Laishan Airport": ("Yantai", "China"),
    "Wenzhou Longwan International Airport": ("Wenzhou", "China"),
    "Kempegowda International Airport": ("Bangalore", "India"),
    "Auckland International Airport": ("Auckland", "New Zealand"),
    "Ibiza Airport": ("Ibiza", "Spain"),
    "Belgrade Nikola Tesla Airport": ("Belgrade", "Serbia"),
    "Catania-Fontanarossa Airport": ("Catania", "Italy"),
}
